name: Cosign & Git Actions to Harbor 
run-name: ${{ github.actor }} is running DevSecOps pipeline for Spring Backend 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: harbor.cccr-opensource.com/nuitciel/cccr_project1_backend
  REGISTRY: harbor.cccr-opensource.com
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and Push Docker Image
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USER }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          ./gradlew bootBuildImage -x test --imageName=$IMAGE_NAME:${{ github.sha }}
          echo $HARBOR_PASSWORD | docker login $REGISTRY -u $HARBOR_USER --password-stdin
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Install Cosign
        run: |
          wget https://github.com/sigstore/cosign/releases/download/v2.4.0/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Download Cosign Key
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
        run: echo "$COSIGN_KEY" > cosign.key

      - name: Sign Docker Image with Cosign
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          yes | cosign sign --key cosign.key $IMAGE_NAME:${{ github.sha }}

      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Build succeeded for commit to Harbor: ${{ github.sha }}"}' $SLACK_WEBHOOK_URL

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Build failed for commit to Harbor: ${{ github.sha }}"}' $SLACK_WEBHOOK_URL

